# Generated by Django 4.2.3 on 2023-10-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access",
            field=models.TextField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="refresh",
            field=models.TextField(editable=False, null=True, unique=True),
        ),
    ]
